export {default as SpotifyGeneratorPage} from './SpotifyGeneratorPage'
export {default as LandingPage} from './LandingPage'
export {default as CookiesPage} from './CookiesPage'
export {default as TermsPage} from './TermsPage'
export {default as PrivacyPage} from './PrivacyPage'
export {default as ErrorPage} from './ErrorPage'
